---

- name: Load our hosts from hosts.yml or if defined an alternate path
  include_vars:
    file: "{{ hosts_file|default(playbook_dir + '/hosts.yml') }}"
  tags:
    - always

- block:
    - name: Add our hosts to the inventory
      include: "add-hosts.yml"
      with_items: "{{ hosts.groups }}"
      loop_control:
        loop_var: hosts_data
